version: "3.9"

services:
  sartu.app:
    build: .
    container_name: sartu.app
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    networks:
      - sartu-network

  sartu.node:
    image: node:21.6.1
    container_name: sartu.node
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    command: ["npm", "run", "dev"]
    ports:
      - "5173:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true   # Necesario para hot reload dentro de Docker
    networks:
      - sartu-network

  sartu.nginx:
    image: nginx:alpine
    container_name: sartu.nginx
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - sartu.app
    networks:
      - sartu-network

  sartu.db:
    image: mysql:8.0
    container_name: sartu.db
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: rk_sartu
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: 123456
      MYSQL_ROOT_HOST: "%"      
    volumes:
      - sartu_db_data:/var/lib/mysql
    networks:
      - sartu-network

volumes:
  sartu_db_data:

networks:
  sartu-network:
    driver: bridge
